---
title: "Bruna Lab Code of Conduct"
author: "Emilio M. Bruna"
date: "updated: `r Sys.Date()`"
header-includes:
   - \usepackage[default]{sourcesanspro}
   - \usepackage[T1]{fontenc}
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  pdf_document: default
  html_document:
    df_print: paged
  rmdformats::robobook: default
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# Lab Code of Conduct
I am committed to providing a safe, inclusive, and supportive environment for all lab members and visitors. With that in mind, this Code of Conduct will be enforced as needed and applies to both our campus- and field-based activities.

# Philosophy
Safe, inclusive, and supportive environments are built on an underlying philosophy of mutual respect and constant effort by all lab members. We are collectively responsible for create and maintaining the environment that allows us to develop and advance both personally and professionally. Discrimination or harassment based on racial or ethnic background, citizenship status, religious beliefs (or lack thereof), political affiliation, gender identity/expression, sexual orientation, dis/ability status, appearance or body size will not be tolerated. We do not tolerate any form of harassment or discrimination by or of members of our community.

We are committed to supporting and training a diverse scientific workforce. Current and former group members comprise a variety of racial and ethnic backgrounds from the U.S. and other countries, members of the LGBTQ community, and first-generation college students. They have gone on to work in settings including the private sector, NGOs, academia, and the armed forces.

# General Guidelines

All communication, including online and in-person, should be appropriate for a diverse audience that includes people of many different backgrounds. Sexual or discriminatory language and imagery is not appropriate at any time.

Be kind to others. Do not insult or put down other contributors. 

People in our lab grew up in many different countries. We will not tolerate behavior and language that denigrates other countries and cultures. It is natural to be curious about one another's backgrounds and cultures. Be mindful of how you ask questions to those from other countries to avoid offense; be mindful that people may ask questions because they are genuinely interested in learning more about your country without realizng they are offending. 

Lab members grew up several different languages, and many are writing a thesis, taking classes, or doing field work in a  language they are still learning. This is challenging and commendable. Be generous in supporting each other (reviewing drafts, assisting with translations) and be understanding if people may use certain words or phrases without realizing the different ways such language can be interpreted. 

In general, assume that others are acting in good faith; this includes when they make suggestions or give criticism. Assume the best of each other.

Harassment and sexist, racist, or exclusionary jokes are not appropriate.  Be aware that your actions can be hurtful to others or contribute to a negative environment even if you had no intent of harm. Listen. Offer a genuine apology.  Commit to learning and doing better. Commit to helping others learn. We may all come from different cultural contexts, but we are all working in this specific one.

Give everyone a chance to talk and an opportunity to contribute.

# Enforcement and Reporting Mechanisms


Unacceptable behavior includes, but is not limited to, offensive verbal comments related to gender, sexual orientation, disability, physical appearance, body size, race, religion, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of discussions, inappropriate physical contact, and unwelcome sexual attention.

Lab members are expected to abide by these policies at all lab-related work events, such as conferences, workshops, etc.
Participants asked to stop any harassing or discriminatory behavior are expected to comply immediately.

If you are being harassed, notice that someone else is being harassed, or have any concerns about potential violations, please contact Emilio immediately. If Emilio is the cause of your concern or you are uncomfortable talking to them directly for any reason, ---- (mailto:mail@mail.com) is a good informal point of contact; she was an early lab member, does not work for us or the University of Florida, and because of her career path does not rely on Emilio in any way. She has agreed to mediate and discuss issues confidentially if desired. Concerns can also be directed to the [UF Ombuds Office](https://www.ombuds.ufl.edu/).

If inappropriate behavior persists, the issue will be escalated according to UF policies; for more information please see the [UF Office for Accessibility and gender Equity](https://titleix.ufl.edu/)

### License & Acknowledgments

This work is licensed under CC BY 4.0.

Material in this code of conduct derives from the Weecology Lab Code of Conduct (License: CC BY 4.0), Whitaker Lab Code of Conduct (License: MIT), the Bahlai Lab Code of Conduct (License: CC BY 4.0), and the Brown Lab Code of Conduct (License: CC BY 3.0).
